In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
train_data = pd.read_csv('../data/train.csv')
test_data = pd.read_csv('../data/test.csv')

In [18]:
train_test = [train_data, test_data]

for dataset in train_test:
    dataset['Title'] = (dataset['Name']
    .str.extract(' ([A-Za-z]+)\.', expand=False)
    .replace(['Lady', 'Countess','Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], "Rare")
    .replace({'Mlle': 'Miss', 'Ms': 'Miss', 'Mme': 'Mrs'}))

<>:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
<>:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
/var/folders/17/dwmdxgxd6f3d9tws818t6_8c0000gp/T/ipykernel_56130/2923414641.py:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
  .str.extract(' ([A-Za-z]+)\.', expand=False)

In [19]:
train_data['Age'] = train_data['Age'].fillna(train_data.groupby('Title')['Age'].transform('median'))
test_data['Age'] = test_data['Age'].fillna(test_data.groupby('Title')['Age'].transform('median'))

train_data = pd.get_dummies(train_data, columns=["Title"],dtype=int)
test_data = pd.get_dummies(test_data, columns=["Title"],dtype=int)
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0

In [20]:
train_data['Sex'] = train_data['Sex'].replace({'male': 0, 'female': 1})
test_data['Sex'] = test_data['Sex'].replace({'male': 0, 'female': 1})
train_data.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0
5,6,0,3,"Moran, Mr. James",0,30.0,0,0,330877,8.4583,NaN,Q,0,0,1,0,0
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,17463,51.8625,E46,S,0,0,1,0,0
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.0,3,1,349909,21.0750,NaN,S,1,0,0,0,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.0,0,2,347742,11.1333,NaN,S,0,0,0,1,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.0,1,0,237736,30.0708,NaN,C,0,0,0,1,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",1,4.0,1,1,PP 9549,16.7000,G6,S,0,1,0,0,0
11,12,1,1,"Bonnell, Miss. Elizabeth",1,58.0,0,0,113783,26.5500,C103,S,0,1,0,0,0
12,13,0,3,"Saundercock, Mr. William Henry",0,20.0,0,0,A/5. 2151,8.0500,NaN,S,0,0,1,0,0
13,14,0,3,"Andersson, Mr. Anders Johan",0,39.0,1,5,347082,31.2750,NaN,S,0,0,1,0,0
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",1,14.0,0,0,350406,7.8542,NaN,S,0,1,0,0,0

In [21]:
train_data = train_data.drop('Name', axis=1)
test_data = test_data.drop('Name', axis=1)
train_data.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,0,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,1,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,1,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,0,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0

In [22]:
drop_cols = ['Ticket', 'Cabin', 'PassengerId']
train_data = train_data.drop(drop_cols, axis=1)
test_data = test_data.drop(drop_cols, axis=1)

train_data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,0,3,0,22.0,1,0,7.2500,S,0,0,1,0,0
1,1,1,1,38.0,1,0,71.2833,C,0,0,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,0,1,0,0,0
3,1,1,1,35.0,1,0,53.1000,S,0,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,0,0,1,0,0

In [23]:
train_data['Embarked'] = train_data['Embarked'].fillna('S')

In [24]:
test_data['Fare'] = test_data['Fare'].fillna(test_data.groupby('Pclass')['Fare'].transform('median'))
test_data.isnull().sum()

Pclass          0
Sex             0
Age             0
SibSp           0
Parch           0
Fare            0
Embarked        0
Title_Master    0
Title_Miss      0
Title_Mr        0
Title_Mrs       0
Title_Rare      0
dtype: int64

In [25]:
train_test = [train_data, test_data]

for dataset in train_test:
    dataset['Embarked'] = dataset['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

#SibSP = number of siblings / spouses aboard the Titanic, #Parch = number of parents / children aboard the Titanic

train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1

train_data.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,FamilySize
0,0,3,0,22.0,1,0,7.2500,0,0,0,1,0,0,2
1,1,1,1,38.0,1,0,71.2833,1,0,0,0,1,0,2
2,1,3,1,26.0,0,0,7.9250,0,0,1,0,0,0,1
3,1,1,1,35.0,1,0,53.1000,0,0,0,0,1,0,2
4,0,3,0,35.0,0,0,8.0500,0,0,0,1,0,0,1
5,0,3,0,30.0,0,0,8.4583,2,0,0,1,0,0,1
6,0,1,0,54.0,0,0,51.8625,0,0,0,1,0,0,1
7,0,3,0,2.0,3,1,21.0750,0,1,0,0,0,0,5
8,1,3,1,27.0,0,2,11.1333,0,0,0,0,1,0,3
9,1,2,1,14.0,1,0,30.0708,1,0,0,0,1,0,2

In [26]:
train_data = train_data.drop(['SibSp', 'Parch'], axis=1)
test_data = test_data.drop(['SibSp', 'Parch'], axis=1)

train_data.head()

,Survived,Pclass,Sex,Age,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,FamilySize
0,0,3,0,22.0,7.2500,0,0,0,1,0,0,2
1,1,1,1,38.0,71.2833,1,0,0,0,1,0,2
2,1,3,1,26.0,7.9250,0,0,1,0,0,0,1
3,1,1,1,35.0,53.1000,0,0,0,0,1,0,2
4,0,3,0,35.0,8.0500,0,0,0,1,0,0,1

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(11, 16)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(16, 8)
        self.fc3 = nn.Linear(8, 1) # output layer

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.relu(self.fc2(x))
        out = self.fc3(x)
        return out

model = Net().to(device)
loss_fn = nn.BCEWithLogitsLoss() #there are different type of loss functions BCEW is for 0 and 1 output -> study different type of lossfn 
optimizer = optim.Adam(model.parameters(), lr=0.005) #there are different type of gradient decent -> study different type of opt function

X_numpy = train_data.drop('Survived', axis=1).values.astype(np.float32)
y_numpy = train_data['Survived'].values.astype(np.float32)

X_train_raw, X_val_raw, y_train_raw, y_val_raw = train_test_split(
    X_numpy, y_numpy, test_size=0.2, random_state=42, stratify=y_numpy
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_raw)
X_val_scaled = scaler.transform(X_val_raw)

X_train = torch.tensor(X_train_scaled, dtype=torch.float32, device=device) #we don't put requires_grad=True here because we don't need gradient of input against y
y_train = torch.tensor(y_train_raw, dtype=torch.float32, device=device).unsqueeze(1)

X_val = torch.tensor(X_val_scaled, dtype=torch.float32, device=device)
y_val = torch.tensor(y_val_raw, dtype=torch.float32, device=device).unsqueeze(1)

# 6. Training Loop with Early Stopping
max_epochs = 1000
patience = 30           # Stop if val loss doesn't improve for 30 epochs
best_val_loss = float('inf')
patience_counter = 0

for epoch in range(max_epochs):
    # Training
    model.train()
    optimizer.zero_grad()
    train_pred = model(X_train)
    train_loss = loss_fn(train_pred, y_train)
    train_loss.backward()
    optimizer.step()

    # Validation
    model.eval()
    with torch.no_grad():
        val_pred = model(X_val)
        val_loss = loss_fn(val_pred, y_val).item()

    # Early Stopping check
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        patience_counter = 0  # Reset
    else:
        patience_counter += 1

    if patience_counter >= patience:
        print(f" Stopped early at epoch {epoch + 1}! Best Val Loss: {best_val_loss:.4f}")
        break

    if (epoch + 1) % 50 == 0:
        print(f"Epoch [{epoch + 1}/{max_epochs}] | Train Loss: {train_loss.item():.4f} | Val Loss: {val_loss:.4f}")

Epoch [50/1000] | Train Loss: 0.4327 | Val Loss: 0.4345
Epoch [100/1000] | Train Loss: 0.3733 | Val Loss: 0.4065
 Stopped early at epoch 111! Best Val Loss: 0.3971

In [29]:
model.eval()
with torch.no_grad():
    # 1. Get raw output logits for validation data
    val_logits = model(X_val)
    
    # 2. Convert logits to probabilities (0.0 to 1.0)
    val_probs = torch.sigmoid(val_logits)
    
    # 3. Convert probabilities to 0 or 1 predictions (threshold at 0.5)
    val_preds = (val_probs >= 0.5).float()
    
    # 4. Compare predictions with actual y_val targets
    correct = (val_preds == y_val).sum().item()
    total = y_val.size(0)
    accuracy = (correct / total) * 100

print(f" Validation Accuracy: {accuracy:.2f}%")

 Validation Accuracy: 83.24%