In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
train_data = pd.read_csv('../data/train.csv')
test_data = pd.read_csv('../data/test.csv')

In [17]:
train_test = [train_data, test_data]

for dataset in train_test:
    dataset['Title'] = (dataset['Name']
    .str.extract(' ([A-Za-z]+)\.', expand=False)
    .replace(['Lady', 'Countess','Capt', 'Col', 'Don', 'Dr', 'Major', 'Rev', 'Sir', 'Jonkheer', 'Dona'], "Rare")
    .replace({'Mlle': 'Miss', 'Ms': 'Miss', 'Mme': 'Mrs'}))

<>:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
<>:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
/var/folders/17/dwmdxgxd6f3d9tws818t6_8c0000gp/T/ipykernel_10037/2923414641.py:5: SyntaxWarning: "\." is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\."? A raw string is also an option.
  .str.extract(' ([A-Za-z]+)\.', expand=False)

In [18]:
train_data['Age'] = train_data['Age'].fillna(train_data.groupby('Title')['Age'].transform('median'))
test_data['Age'] = test_data['Age'].fillna(test_data.groupby('Title')['Age'].transform('median'))

train_data = pd.get_dummies(train_data, columns=["Title"],dtype=int)
test_data = pd.get_dummies(test_data, columns=["Title"],dtype=int)
train_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0

In [19]:
train_data['Sex'] = train_data['Sex'].replace({'male': 0, 'female': 1})
test_data['Sex'] = test_data['Sex'].replace({'male': 0, 'female': 1})
train_data.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,"Braund, Mr. Owen Harris",0,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",1,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,"Heikkinen, Miss. Laina",1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",1,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,"Allen, Mr. William Henry",0,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0
5,6,0,3,"Moran, Mr. James",0,30.0,0,0,330877,8.4583,NaN,Q,0,0,1,0,0
6,7,0,1,"McCarthy, Mr. Timothy J",0,54.0,0,0,17463,51.8625,E46,S,0,0,1,0,0
7,8,0,3,"Palsson, Master. Gosta Leonard",0,2.0,3,1,349909,21.0750,NaN,S,1,0,0,0,0
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",1,27.0,0,2,347742,11.1333,NaN,S,0,0,0,1,0
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",1,14.0,1,0,237736,30.0708,NaN,C,0,0,0,1,0
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",1,4.0,1,1,PP 9549,16.7000,G6,S,0,1,0,0,0
11,12,1,1,"Bonnell, Miss. Elizabeth",1,58.0,0,0,113783,26.5500,C103,S,0,1,0,0,0
12,13,0,3,"Saundercock, Mr. William Henry",0,20.0,0,0,A/5. 2151,8.0500,NaN,S,0,0,1,0,0
13,14,0,3,"Andersson, Mr. Anders Johan",0,39.0,1,5,347082,31.2750,NaN,S,0,0,1,0,0
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",1,14.0,0,0,350406,7.8542,NaN,S,0,1,0,0,0

In [20]:
train_data = train_data.drop('Name', axis=1)
test_data = test_data.drop('Name', axis=1)
train_data.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,1,0,3,0,22.0,1,0,A/5 21171,7.2500,NaN,S,0,0,1,0,0
1,2,1,1,1,38.0,1,0,PC 17599,71.2833,C85,C,0,0,0,1,0
2,3,1,3,1,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,0,1,0,0,0
3,4,1,1,1,35.0,1,0,113803,53.1000,C123,S,0,0,0,1,0
4,5,0,3,0,35.0,0,0,373450,8.0500,NaN,S,0,0,1,0,0

In [21]:
drop_cols = ['Ticket', 'Cabin', 'PassengerId']
train_data = train_data.drop(drop_cols, axis=1)
test_data = test_data.drop(drop_cols, axis=1)

train_data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare
0,0,3,0,22.0,1,0,7.2500,S,0,0,1,0,0
1,1,1,1,38.0,1,0,71.2833,C,0,0,0,1,0
2,1,3,1,26.0,0,0,7.9250,S,0,1,0,0,0
3,1,1,1,35.0,1,0,53.1000,S,0,0,0,1,0
4,0,3,0,35.0,0,0,8.0500,S,0,0,1,0,0

In [22]:
train_data['Embarked'] = train_data['Embarked'].fillna('S')

In [23]:
test_data['Fare'] = test_data['Fare'].fillna(test_data.groupby('Pclass')['Fare'].transform('median'))
test_data.isnull().sum()

Pclass          0
Sex             0
Age             0
SibSp           0
Parch           0
Fare            0
Embarked        0
Title_Master    0
Title_Miss      0
Title_Mr        0
Title_Mrs       0
Title_Rare      0
dtype: int64

In [24]:
train_test = [train_data, test_data]

for dataset in train_test:
    dataset['Embarked'] = dataset['Embarked'].map({'S': 0, 'C': 1, 'Q': 2})

#SibSP = number of siblings / spouses aboard the Titanic, #Parch = number of parents / children aboard the Titanic

train_data['FamilySize'] = train_data['SibSp'] + train_data['Parch'] + 1
test_data['FamilySize'] = test_data['SibSp'] + test_data['Parch'] + 1

train_data.head(10)

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,FamilySize
0,0,3,0,22.0,1,0,7.2500,0,0,0,1,0,0,2
1,1,1,1,38.0,1,0,71.2833,1,0,0,0,1,0,2
2,1,3,1,26.0,0,0,7.9250,0,0,1,0,0,0,1
3,1,1,1,35.0,1,0,53.1000,0,0,0,0,1,0,2
4,0,3,0,35.0,0,0,8.0500,0,0,0,1,0,0,1
5,0,3,0,30.0,0,0,8.4583,2,0,0,1,0,0,1
6,0,1,0,54.0,0,0,51.8625,0,0,0,1,0,0,1
7,0,3,0,2.0,3,1,21.0750,0,1,0,0,0,0,5
8,1,3,1,27.0,0,2,11.1333,0,0,0,0,1,0,3
9,1,2,1,14.0,1,0,30.0708,1,0,0,0,1,0,2

In [25]:
train_data = train_data.drop(['SibSp', 'Parch'], axis=1)
test_data = test_data.drop(['SibSp', 'Parch'], axis=1)

train_data.head()

,Survived,Pclass,Sex,Age,Fare,Embarked,Title_Master,Title_Miss,Title_Mr,Title_Mrs,Title_Rare,FamilySize
0,0,3,0,22.0,7.2500,0,0,0,1,0,0,2
1,1,1,1,38.0,71.2833,1,0,0,0,1,0,2
2,1,3,1,26.0,7.9250,0,0,1,0,0,0,1
3,1,1,1,35.0,53.1000,0,0,0,0,1,0,2
4,0,3,0,35.0,8.0500,0,0,0,1,0,0,1

In [26]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import wandb

# 1. Define Sweep Configuration
sweep_config = {
    "method": "bayes",  # Options: 'bayes', 'random', 'grid'
    "metric": {
        "name": "val_loss",
        "goal": "minimize"
    },
    "parameters": {
        "learning_rate": {
            "distribution": "log_uniform_values",
            "min": 0.0001,
            "max": 0.01
        },
        "hidden_1": {
            "values": [16, 32, 64]
        },
        "hidden_2": {
            "values": [8, 16, 32]
        },
        "Dropout": {
            "values": [0.0, 0.1, 0.2, 0.3, 0.5]
        },
        "epochs": {
            "value": 1000
        },
        "patience": {
            "value": 30
        },
        "architecture": {
            "value": "MLP"
        },
        "dataset": {
            "value": "Titanic_survival"
        }
    }
}

# 2. Wrap everything in a single training function
def train():
    # Initialize run inside the function without fixed config dict
    run = wandb.init()
    config = run.config
    
    device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

    # Define Model dynamically using current run's config
    class Net(nn.Module):
        def __init__(self):
            super().__init__()
            self.fc1 = nn.Linear(11, config.hidden_1)
            self.relu = nn.ReLU()
            self.dropout = nn.Dropout(p=config.Dropout)
            self.fc2 = nn.Linear(config.hidden_1, config.hidden_2)
            self.fc3 = nn.Linear(config.hidden_2, 1)

        def forward(self, x):
            x = self.relu(self.fc1(x))
            x = self.dropout(x)
            x = self.relu(self.fc2(x))
            x = self.dropout(x)
            out = self.fc3(x)
            return out

    model = Net().to(device)
    loss_fn = nn.BCEWithLogitsLoss()
    optimizer = optim.Adam(model.parameters(), lr=config.learning_rate)

    # Data Processing
    X_numpy = train_data.drop('Survived', axis=1).values.astype(np.float32)
    y_numpy = train_data['Survived'].values.astype(np.float32)

    X_train_raw, X_val_raw, y_train_raw, y_val_raw = train_test_split(
        X_numpy, y_numpy, test_size=0.2, random_state=42, stratify=y_numpy
    )

    scaler = StandardScaler()
    X_train_scaled = scaler.fit_transform(X_train_raw)
    X_val_scaled = scaler.transform(X_val_raw)

    X_train = torch.tensor(X_train_scaled, dtype=torch.float32, device=device)
    y_train = torch.tensor(y_train_raw, dtype=torch.float32, device=device).unsqueeze(1)

    X_val = torch.tensor(X_val_scaled, dtype=torch.float32, device=device)
    y_val = torch.tensor(y_val_raw, dtype=torch.float32, device=device).unsqueeze(1)

    # Training Loop
    patience = config.patience
    best_val_loss = float('inf')
    patience_counter = 0

    for epoch in range(config.epochs):
        model.train()
        optimizer.zero_grad()
        train_pred = model(X_train)
        train_loss = loss_fn(train_pred, y_train)
        train_loss.backward()
        optimizer.step()

        train_acc = ((torch.sigmoid(train_pred) > 0.5) == y_train).float().mean().item()

        model.eval()
        with torch.no_grad():
            val_pred = model(X_val)
            val_loss = loss_fn(val_pred, y_val).item()
            val_acc = ((torch.sigmoid(val_pred) > 0.5) == y_val).float().mean().item()

        run.log({
            "epoch": epoch + 1,
            "train_loss": train_loss.item(),
            "train_acc": train_acc,
            "val_loss": val_loss,
            "val_acc": val_acc
        })

        if val_loss < best_val_loss:
            best_val_loss = val_loss
            patience_counter = 0
        else:
            patience_counter += 1

        if patience_counter >= patience:
            break

    run.summary["best_val_loss"] = best_val_loss
    run.finish()

# 3. Initialize & Run the Sweep Agent
sweep_id = wandb.sweep(
    sweep=sweep_config,
    entity="88-eateatyumm-imperial-college-london",
    project="Titanic-ML"
)

# Run 20 different experiment combinations
wandb.agent(sweep_id, function=train, count=20)

Create sweep with ID: wadnri5c
Sweep URL: https://wandb.ai/88-eateatyumm-imperial-college-london/Titanic-ML/sweeps/wadnri5c

wandb: Agent Starting Run: 6f65oiji with config:
wandb: 	Dropout: 0.5
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 64
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.00010527762260754769
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: b4v82649 with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.003350242887329526
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 4cqmvak7 with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 32
wandb: 	learning_rate: 0.007276344495173438
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: f329kq89 with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0008364458143009224
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: hykllgqi with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.003291695719713399
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 65zbxg1n with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 32
wandb: 	learning_rate: 0.002161949085293692
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: cbqvi3bj with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.001660865747860714
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: 3rzxaqwx with config:
wandb: 	Dropout: 0.2
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 64
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0013996986471470818
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 47ui350e with config:
wandb: 	Dropout: 0.2
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 64
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0014997860149895176
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: p94bwj9n with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 64
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.004341115857925205
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 1bc07u5p with config:
wandb: 	Dropout: 0.2
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0024954236719126745
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: w0dk1x2y with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.002640409175757158
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: m09854mr with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0003502702255253583
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: sa66kng0 with config:
wandb: 	Dropout: 0.2
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 8
wandb: 	learning_rate: 0.0055826051523006305
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 60rt24vs with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 8
wandb: 	learning_rate: 0.001600440235066558
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: ck7fbvpp with config:
wandb: 	Dropout: 0.5
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 32
wandb: 	learning_rate: 0.0008973152099355722
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: 21qy6k9a with config:
wandb: 	Dropout: 0
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 32
wandb: 	learning_rate: 0.009974294787794932
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: ysa1634y with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 16
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0018660373928233527
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Sweep Agent: Waiting for job.
wandb: Job received.
wandb: Agent Starting Run: janvn6cj with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0016245748218518636
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

wandb: Agent Starting Run: wadcs3qb with config:
wandb: 	Dropout: 0.1
wandb: 	architecture: MLP
wandb: 	dataset: Titanic_survival
wandb: 	epochs: 1000
wandb: 	hidden_1: 32
wandb: 	hidden_2: 16
wandb: 	learning_rate: 0.0014939674451982608
wandb: 	patience: 30
wandb: [wandb.login()] Loaded credentials for https://api.wandb.ai from /Users/koshiro/.netrc.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [28]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# 1. Optimal Configuration
best_config = {
    "learning_rate": 0.0016004,
    "hidden_1": 16,
    "hidden_2": 8,
    "Dropout": 0.1,
    "epochs": 317,  # Exact optimal number of epochs
    "architecture": "MLP",
    "dataset": "Titanic_survival"
}

device = torch.device("mps" if torch.backends.mps.is_available() else "cpu")

# 2. Model Definition
class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.fc1 = nn.Linear(11, best_config["hidden_1"])
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(p=best_config["Dropout"])
        self.fc2 = nn.Linear(best_config["hidden_1"], best_config["hidden_2"])
        self.fc3 = nn.Linear(best_config["hidden_2"], 1)

    def forward(self, x):
        x = self.relu(self.fc1(x))
        x = self.dropout(x)
        x = self.relu(self.fc2(x))
        x = self.dropout(x)
        out = self.fc3(x)
        return out

model = Net().to(device)
loss_fn = nn.BCEWithLogitsLoss()
optimizer = optim.Adam(model.parameters(), lr=best_config["learning_rate"])

# 3. Data Processing
X_numpy = train_data.drop('Survived', axis=1).values.astype(np.float32)
y_numpy = train_data['Survived'].values.astype(np.float32)

X_train_raw, X_val_raw, y_train_raw, y_val_raw = train_test_split(
    X_numpy, y_numpy, test_size=0.2, random_state=42, stratify=y_numpy
)

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_raw)
X_val_scaled = scaler.transform(X_val_raw)

X_train = torch.tensor(X_train_scaled, dtype=torch.float32, device=device)
y_train = torch.tensor(y_train_raw, dtype=torch.float32, device=device).unsqueeze(1)

X_val = torch.tensor(X_val_scaled, dtype=torch.float32, device=device)
y_val = torch.tensor(y_val_raw, dtype=torch.float32, device=device).unsqueeze(1)

# 4. Train directly for 317 epochs
for epoch in range(best_config["epochs"]):
    model.train()
    optimizer.zero_grad()
    train_pred = model(X_train)
    train_loss = loss_fn(train_pred, y_train)
    train_loss.backward()
    optimizer.step()

# 5. Save final weights
torch.save(model.state_dict(), "best_titanic_model.pth")
print(f"Trained for exactly {best_config['epochs']} epochs. Model saved as 'best_titanic_model.pth'.")

Trained for exactly 317 epochs. Model saved as 'best_titanic_model.pth'.

In [29]:
model.eval()
with torch.no_grad():
    # 1. Get raw output logits for validation data
    val_logits = model(X_val)
    
    # 2. Convert logits to probabilities (0.0 to 1.0)
    val_probs = torch.sigmoid(val_logits)
    
    # 3. Convert probabilities to 0 or 1 predictions (threshold at 0.5)
    val_preds = (val_probs >= 0.5).float()
    
    # 4. Compare predictions with actual y_val targets
    correct = (val_preds == y_val).sum().item()
    total = y_val.size(0)
    accuracy = (correct / total) * 100

print(f" Validation Accuracy: {accuracy:.2f}%")

 Validation Accuracy: 84.36%